# Generated by Django 4.2.7 on 2023-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
