# Generated by Django 4.2.7 on 2023-12-07 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_account_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(blank=True)),
                ('course_week', models.IntegerField(choices=[(1, 'Week 2'), (2, 'Week 4'), (3, 'Week 8'), (4, 'Week 10'), (5, 'Week 12'), (6, 'Week 18')])),
                ('price', models.IntegerField(default='')),
                ('outcomes', models.TextField()),
                ('course_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
