# Generated by Django 4.2.7 on 2023-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
