# Generated by Django 4.2.7 on 2024-01-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_course_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_file',
        ),
    ]
