# Generated by Django 4.2.7 on 2024-01-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_assessment_assessment_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
