# Generated by Django 4.2.7 on 2024-01-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_file',
        ),
    ]
