# Generated by Django 4.2.7 on 2024-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_assessment_assessment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
