# Generated by Django 4.2.7 on 2024-01-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.TextField(default='', max_length=50),
        ),
    ]
