# Generated by Django 4.2.7 on 2024-01-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAssessment',
        ),
    ]
